[general]
log_level="info"

[integration]
enabled=["mqtt"]

[integration.mqtt]
server="tcp://mosquitto:1883"
json=true
event_topic_template="gateway/{{ .GatewayID }}/event/{{ .EventType }}"
state_topic_template="gateway/{{ .GatewayID }}/state/{{ .StateType }}"
command_topic_template="gateway/{{ .GatewayID }}/command/#"

[backend]
enabled="semtech_udp"

[backend.semtech_udp]
udp_bind="0.0.0.0:1700"
skip_crc_check=false
fake_rx_time=false
