[logging]
level="info"

[postgresql]
dsn="postgres://chirpstack:chirpstack@postgres/chirpstack?sslmode=disable"

[redis]
servers=["redis://redis/"]

[api]
bind="0.0.0.0:8080"
secret="replace-with-a-strong-secret"

[integration]
enabled=["mqtt"]

[integration.mqtt]
server="tcp://mosquitto:1883"
json=true
event_topic_template="application/{{application_id}}/device/{{dev_eui}}/event/{{event}}"
command_topic_template="application/{{application_id}}/device/{{dev_eui}}/command/{{command}}"

[network]
enabled_regions=["eu868"]

[monitoring]
bind="0.0.0.0:8090"
