apiVersion: 1

policies:
  - orgId: 1
    receiver: iot-webhook
    group_by:
      - alertname
      - severity
    group_wait: 30s
    group_interval: 2m
    repeat_interval: 30m

resetPolicies:
  - orgId: 1
